//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OsWebsite.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Advertise
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string Summary { get; set; }
        public string Image { get; set; }
        public string ImageSmall { get; set; }
        public Nullable<int> Width { get; set; }
        public Nullable<int> Height { get; set; }
        public string Link { get; set; }
        public string Target { get; set; }
        public string ContentDetail { get; set; }
        public int Position { get; set; }
        public int IsOrder { get; set; }
        public bool IsActive { get; set; }
        public int IDLang { get; set; }
        public Nullable<int> MenuID { get; set; }
        public Nullable<int> MenuID2 { get; set; }
    
        public virtual Language Language { get; set; }
    }
}
