//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OsWebsite.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Comment
    {
        public int ID { get; set; }
        public string NameUser { get; set; }
        public string Email { get; set; }
        public string website { get; set; }
        public string Content { get; set; }
        public string Title { get; set; }
        public Nullable<System.DateTime> DateComment { get; set; }
        public Nullable<bool> IsActive { get; set; }
    }
}
