//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OsWebsite.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Gallery
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Gallery()
        {
            this.GalleryDetail = new HashSet<GalleryDetail>();
        }
    
        public int ID { get; set; }
        public string Name { get; set; }
        public string Tag { get; set; }
        public string Images { get; set; }
        public string Link { get; set; }
        public Nullable<int> Position { get; set; }
        public int IDLang { get; set; }
        public int IsOrder { get; set; }
        public bool IsActive { get; set; }
    
        public virtual Language Language { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GalleryDetail> GalleryDetail { get; set; }
    }
}
