//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OsWebsite.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class GalleryDetail
    {
        public int ID { get; set; }
        public int GalleryID { get; set; }
        public string Name { get; set; }
        public string Images { get; set; }
        public string Link { get; set; }
        public Nullable<int> Position { get; set; }
        public int IsOrder { get; set; }
        public bool IsActive { get; set; }
    
        public virtual Gallery Gallery { get; set; }
    }
}
