//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OsWebsite.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MenuType
    {
        public int ID { get; set; }
        public int MenuPageID { get; set; }
        public int MenuID { get; set; }
        public Nullable<int> IDLang { get; set; }
    
        public virtual Menu Menu { get; set; }
        public virtual MenuPage MenuPage { get; set; }
    }
}
