//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OsWebsite.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class NewsImages
    {
        public int ID { get; set; }
        public int NewsID { get; set; }
        public string Name { get; set; }
        public string Images { get; set; }
        public string Decription { get; set; }
        public int IsOrder { get; set; }
        public bool IsActive { get; set; }
    
        public virtual News News { get; set; }
    }
}
