//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OsWebsite.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Product()
        {
            this.OrderDetail = new HashSet<OrderDetail>();
            this.ProductImages = new HashSet<ProductImages>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public string Tag { get; set; }
        public int GroupProductId { get; set; }
        public string Image { get; set; }
        public string Summary { get; set; }
        public string ContentDetail { get; set; }
        public string ContentDetail2 { get; set; }
        public Nullable<double> Price { get; set; }
        public Nullable<double> PriceOld { get; set; }
        public string Discount { get; set; }
        public Nullable<int> Amount { get; set; }
        public Nullable<int> Views { get; set; }
        public Nullable<int> Priority { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public string Title { get; set; }
        public string Description { get; set; }
        public string Keyword { get; set; }
        public int IDLang { get; set; }
        public int IsOrder { get; set; }
        public bool Hot { get; set; }
        public bool New { get; set; }
        public bool Main { get; set; }
        public bool IsActive { get; set; }
        public string MaSanPham { get; set; }
    
        public virtual Menu Menu { get; set; }
        public virtual Module Module { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrderDetail> OrderDetail { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProductImages> ProductImages { get; set; }
    }
}
