//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OsWebsite.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Visitor
    {
        public int MaTB { get; set; }
        public Nullable<System.DateTime> Thoigian { get; set; }
        public Nullable<long> SoTruyCap { get; set; }
    }
}
